sudo: required
services:
- docker
before_install:
- docker-compose --version
script:
- "./build.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: q5tqdWJ9Z8EfRw6WTlBwh8rcdXGcUdS8rwunRsza7x69hFwuou4yL0jiBJ/QXtKzpRA3FIFAHsKpbhljIgGJoAnKvDS35EhfXnZIQ4X4f2ERV8nRLTci+3h/2vxoYQTYSVCGDS5mBpURruGrnXilzpPpLhWaCUotdcLzig2PiO+wuaL6oyagg+EzYepMHsqzAeKOR1NcG8F2oHxUJo0frSjTJb6w5jY897uoHmgJrPDwruJdGClInKRv/nfZgsB9YvMTi5bpK9OL+2e6thttdxqGYmk38sZS3MpoCThE7g0kNHPCMz1puFh1tVexpyKXp/o3jCM4e3sRbNpKvaHOKmGsXr5cRr6EemUeX2SLcyzqgmD7Kx2yM8hPHMvSni5KEaJsIakhOYGMrQea+B9VMxV/XOkn9pDiKBqWM3517xDxNVMXp+zN8oao80oIcW37es3mQN48/mwiLsvFjg6PJdX2KIcojt8xdmmRUyVEuI1H1dAuuORv09/FP3Yvf4J0d+29EJF4JPwXX/7o0r03VBM9FT1kZSSEwATX7p42JAfpd2dRPjl1pOuWlYTSCO+oOU0XqItPgaPeJgKIoLdPjRz126Mq8EKzgy9vGi1xScbLPZ9ZUWP7iMnxCi9Hitq5yOPwJSnWb1BtIWerIVTecLeFuJAJNOagBEWWJb6Duw8=
  - secure: TdlpUKeVPHdNZFEgl3ta8GHrcfljpoKMeUjb9cAiKxIl06Ph1HQfC9yXpnWF49eG1BOzu9Xg4/BA4gQTfpVPHeVK1O+46XZ5X6VSawCsE6sbP34C2pWxFfS2U2B8IUPW9ykKRax8hLkD3kqPDQTWQw4+8xvQpbIJWGY8NDqN9oGAghKDB0mmkzY3vaCMqVb1jLsRxKpQ1BjbK+vTGapkQEUhz11szQgI/T+eSd6NEV75U9dUPgczptbcQBI2jVo4FOgGc3SxsYHjynnsDmOQsG7kGGRMPxNfluPIoswUO3S0C90xSOJsvMt5Vs3BIOp+bvIMxMylRkosL8NbiPn0EHISKSJW8yEMahFC+axhz5qGYirlIgWUEjRQnjzoNvDxN5u5X0TYu8qihSiVuEH5BH3qYomYvJXsuRF3sl+3oc56ds6EmICEnDw2L6AlsD7MRw9UcAnlbSlanuJyWmxRSoModBJaRpbAi7T/8jxkzMUZt2YjSUcUx+Cx1A4FpfGTu+Gq+sL+MNrMIs70zepP+X2syy8E9W62uqpIf+8K5aXIWMBwfVqVPnS3mwK/nuCpepWvY7LiI06ZV8oQtxjTgQSiP5QeEEq+54pM5r8hFEFBThLv2pbRq32u5mwaPTKS9wsxomzktIbYmjkitSBZvCyyjxRH3Br898UCbRwXeWM=
