sudo: required
services:
- docker
before_install:
- docker-compose --version
script:
- "./build.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  matrix:
  - secure: zNSQ9rmWBTEgXq5wrdGGtq+Jhq3HAQSaYYl6cNpB/1hsN71l10zHKWC2Ifg96gY6DJVKrskfj1/phZQm/KUQe7l8J4myBDcvQGypkN+raVNQBBYX6lF+FAx87fZUrH4rDdwdACZT0ny7Mi38LBOCq3jf4vSlDaeMWn0P5aUI7N5c6ysT6TZKbp8gz9FpUATiElzAFUPsgJwzgtrRm/wfG3lOmP6K9TM2qogAua59PulA64nXbfHg+bcbNrXJITl9mQMPcWbADMWEdNGPsssRcGJ2ACZQNxbhUIptw4lt9Yb4ExmrZgBIPWU6c2IY4Ab6hmNmcpmubtoSBwMEjxx6NFeAepHe/Hz9qfVdaDnLvR2UUD6BADa4g5ac+uKTmgMIW+3sn6fR5c8WvI0gPEy0m2t1BpMFVajm6M0J4bDMJvzpFKqpq3Ou4ykISS7irS8YG0IonA3nzkQcm3zf1JtqVJmgPoOyfagDJo0ApyWgW5x3d3tr37UMgSOWPRAOak+1450sg78PmqVMJZ0QnBsAEK005WcRdqCNT4cphZgPGDaaVdwYCR20ppDojZCwIqdncJiRtBvq2q23PUrkwTrVBHLtJYlGtSimNJQE842gScJFCaOwp302En5ZRzBfGBcct0R/4+ceCFVJpArXPn2929DTzAFr36YMxVDBX1WPvzI=
  - secure: MhjwZGLA/XcHxp5Nh5jQCD+OdTWShZb0tt0Cm/OyXlReI675ELJ0QMTGLZVTxaYmRK4uUOCV7ojkYwNej00HR4IY0XPz11uW8Kj1HruXtlL6ASPho+p3E4Z6FYLF9wrZEGwoTSFi0TIay0jyeREs/j34QkURfxkqNsVcF/T32hNHlqFE7IzKjkxaSb+IQSI9ZVxnLM/sGl/pPJNTyMlIg0zNNbSCkUASK+yLHYLepT/dPTPyspTQs/jiWqKASZLf40jK9mtqZbPp6gSzC7iE879J0U034Xy0+trxUjM86hIhXKtq7Cwyis/k0nSxPmZbic1386cTY7CRsrs/ScGh1LJpLrJQ5JyYxXDEDhfu8le0y191+OxwR1XleMdwNFE8oWgZ3Y4jlPDV8AXZfbuChGWrgv4ArfXU71jZ+gSDr4J3QPcYGZu/rAn+wUXLMb1S4vYdtADWQ2PvGLAG0lHIuUhVreKJ0ioLZBzaASNWVxAEDRyUqVEJ2sOOVVViDEWO/ihidWAmHM/3jn0FK7xTgGcKqcSs8kPeZcmuD5z6mGPiJRlXI8/tBnzP2bYmTIa5FwmMqh0IbGtVmC4+0nxmqpzRiwHa1Hyv6jROULeOUecFKUsZeU7fo+S3gQT/rf5T4KCqcws67vGtyxwhwKp5RSvtzluYfoe6t5FpQMi0bLo=
