sudo: required
services:
- docker
before_install:
- docker-compose --version
script:
- "./build.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: O+//y4jeC4zsaWU4nGf1zx0RZwm2gJJAvrIy8DNToxCoL3AFbJhuN2kmPstRQEClmGFdHRbO/rCJtaCmSBgTwuf9ma2yq5x9ngpDXFR007BcJiUW5z2SYoZXZiATH5NXmgknRRHj3CqrwxhcPq4xV4XHGtd46IAsiTJdze6v4Wa+Yg1MoXesVYT/cgWRa0G/5WoHa24vfH0p8NAvrl7cH2lGWsKCaOGwRPJxP9ORwBbYOOEGY/d29suBxZDw28b0oVmd7LWDpm+2fpMutbm5NyTY4Rs93IHcUyuftxygc/uXwP4B1OoDxqg4D831NrZR38Z+kLvfihipb3/fHLEENufU/wV+Pqa3jWj+K5e4sIxD0+UropUT77wmiBzwVJuxLZDvCDKe6xT3gZn/ZRC5ShTnZr05dNALbhScCHLDnZXVfl0g+I2gsgg3DsHTOOpPvD8AngME6zKv40sCF2oLBm1trtM/XpsFd+G0UqczvP0Z/Kwkw9tpreIu/gIZxXe5qrLgncYGFDk7ucvg0ZKifdrKC1iC38HuHLl0Lu5DwYNRRiK7o9paCJ5VbmYikcBUggyXfUPeEJQvB8SbTfDg/kDbaDKvcxUX6G/Zz9CGUqHV2bHbSVGCfIU1vF1AVIFcagLv8ii+W2DEIM1Ip1DDTPFtR0aOhwTJx0tAEWzHTLE=
  - secure: Yu2aG0vv5yuAgL0I0HWhe+2qkio5wVSMhi5QswnnWDjo7sC5NZWeIgQUijUu1rd97f1llpToTJU1I89Sxihmz83V+KW4neEXVb3a+PRvkE3VZ8Kx0csSiYR+69wkrmy05DKLBhnQ5Er25IHcCkGdTCSs4mG3a5EPpIqmqd5lp2T1TS6xPQF2p7t5vKyMdGL8X8TkeoeaYTxD5PCRH8MH9ilnPn37G23Hq2pWrc4oGUbdSbGQGhGEHTVJmRzEyaWmAw93eHnnyT0mFmhwuvEiL9SxONA8XHwsIWcbXv2fI5DZUejJESsW/e5mf5gvMg77SoSHANEMtmDv6A6kdNqRECZADXvNHnz5vu6/id7V+Ud3toCOqzi2/ESrkt+iCA/ZF76dvHEjcqNxnV41R74MqP0sfuofD/r8mXlsITI4/Z3GZZMelVrti2gcJkdUZccaXQWIggJq5SGE40paFLczcYmxoqP/TCVtfA1kwJYt/0zK4gBXtquTPoTHZrtxQd5MuX3gj1UwNXDUu0V3vCXZkJfWJBjfG8m91dxKcoflef+xIzwdy3cNE+NXleRYJWopn5IhlB1CNSm00viAxKLWe76TP7VAtyKkDxCtIaE/LwlJVXdIuyaKQ1XbPI8AT/4+iOK+SnzUJcU/JrjCwZlNzwIzTVNqxSjRQn3Nje/m7Hs=
