sudo: required
language: python
python:
  - 3.6
services:
  - docker
before_install:
  - docker-compose --version
script:
  - "./build.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
