sudo: required
services:
- docker
before_install:
- docker-compose --version
script:
- "./build.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: k+W3iP1fAyJ9ctHAt+bnmj3m5VyFg4Qg/AiLWhPKcSLscYWt8x++ifHUv3lnA8wcdxL/DiTyAzSjsLfkJBMKade6YS7CtAFO4DhurQcbkY8bvvht+U/HEQ4/FXRdS1B8+DGe/1PWok/9rK4njO0Dex5gRd1AX9sLBn4FAtyewo66OgfUSrCDlx+rdqUz+St6OnL8P7M+k3XhH5FpPdYUFCGzKp2EwvbVgxFlBZA7EnQp+4pB9chnGdoN5SyfHstH9qXN5KbcLREOl5RKVtr3+0NW1dfHrEol+vihoiWboIWS6/WnveNf1ceMbd4aSY6N+/4vJySvYrR2ajSFJ5PpYQxG133EWudqSkpzLix3GJEqaghSTvWcK+CUlfzMGGAm49CR55yTe6agvrzW2X2oxW50sFyhkNwIJas2Tk6aiHicYc3NaPXUlqVK9yJF7Zi7VnR/kgOt7khCRb2fkc9F8zvxqHkGigK4hT9L+bECKfTYt6akXAHvrGvL2Jr02yeZdaQN1wxwNUxwmLKwD4kx1Vwwv8gNzaiLs2fO4xkHRMcngjhGwCRoNfy/qt4rsC05I64TTqQth/hgxTmzquHPcxYJ2c9lf9JPlo3/xmJoE8pYcNK6Zg9Z+BUvEmyHtNOagbnCPIMFDFIHLYLoL8IXCvMR8/hlgqNzz5Il5kQCn9E=
  - secure: 1WnoX8uie9+ZlAva5OQQ9JK2n66p5IyxYAjjA4hK+hYtbtcR4oU4Tt8HNfvA88o17aYHbRjINKUBWYz9VL6G5XcNfhxGsg96rZJNs9x3SbhW9x91OiANaYYSDbgEPw10UJ7Hos1aEoGzr+dh02GhMLtCR2GDUyidy5ZJUpp052FWA/3+46sodtWhmAvl+mlq8d6zjy7OXzSpz/sT5rgB1L46LekvUPjxJXLdnUc/OvNLy85nnYatNVV04YRAssV4lWggjWcBizh21Z2cwVk+rnlxK48RlUOM4bkpbcbkKYnIme/gCiAlfs7WdkDAqJnQmZJw45pGkTyJgp9oJp+UAwqW75v5Mg2ptbSuShqtS3PxDPjodI1G4VBzB/Wu35/6JGbuTiIuNBIogYAQwL6PNQCS1iNVQrklPW+AgySX+vSuVWxyMqSjM4dwxgI5d3RWjM/faGEX1qtDZpBkVy75Af0sJvChL/XW8S55XtLT0Vm7BtVc8YzcJ6HJ+tNUBPufglVq/HVLRQXAjnwe6qBw2eIhcVwexpKtuFhotzIy9c13cahnkm/CjjG0MgNsYD/Dtsyj1xSFjmNen7ZqlX96mE8fkTR6wanzmiRn/h4r0JKVERILvpsz4XTYwbUlH4g3Go/nejLrAp/PTh0Xt0bVbUg6wI3YFPR7FaE2CXjCEMM=
